export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAILED = "GET_PRODUCT_LIST_FAILED";
export const SET_PRODUCT = "SET_PRODUCT";
export const SIGNIN = "SIGNIN";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
export const CLEAR_SESSION = "CLEAR_SESSION";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_FAILED = "UPDATE_USER_INFO_FAILED";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";

export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES";
export const GET_SUB_CATEGORIES_SUCCESS = "GET_SUB_CATEGORIES_SUCCESS";
export const GET_SUB_CATEGORIES_FAILED = "GET_SUB_CATEGORIES_FAILED";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_TO_CART = "DELETE_TO_CART";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const UPDATE_TO_CART_SUCCESS = "UPDATE_TO_CART_SUCCESS";
export const DELETE_TO_CART_SUCCESS = "DELETE_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";

export const ORDERS = "ORDERS";
export const ORDERS_SUCCESS = "ORDERS_SUCCESS";
export const ORDERS_FAILED = "ORDERS_FAILED";

export const ORDER_LIST = "ORDER_LIST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAILED = "ORDER_LIST_FAILED";

export const LOCATION_SEARCH = "LOCATION_SEARCH";
export const LOCATION_SEARCH_SUCCESS = "LOCATION_SEARCH_SUCCESS";
export const LOCATION_SEARCH_FAILED = "LOCATION_SEARCH_FAILED";

export const SET_USER_LATLONG = "SET_USER_LATLONG";
export const SET_USER_LATLONG_SUCCESS = "SET_USER_LATLONG_SUCCESS";
export const SET_USER_LATLONG_FAILED = "SET_USER_LATLONG_FAILED";

export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const SET_USER_LOCATION_SUCCESS = "SET_USER_LOCATION_SUCCESS";
export const SET_USER_LOCATION_FAILED = "SET_USER_LOCATION_FAILED";

export const IS_GLOBAL = "IS_GLOBAL";

export const SHOW_MAP = "SHOW_MAP";

export const GET_DISTANCE = "GET_DISTANCE";
export const GET_DISTANCE_SUCCESS = "GET_DISTANCE_SUCCESS";
export const GET_DISTANCE_FAILED = "GET_DISTANCE_FAILED";

export const GET_ADDRESSES = "GET_ADDRESSES";
export const GET_ADDRESSES_SUCCESS = "GET_ADDRESSES_SUCCESS";
export const GET_ADDRESSES_FAILED = "GET_ADDRESSES_FAILED";

export const ADD_ADDRESS = "ADD_ADDRESS";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAILED = "ADD_ADDRESS_FAILED";

export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAILED = "UPDATE_ADDRESS_FAILED";

export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILED = "DELETE_ADDRESS_FAILED";

export const SET_CURRENT_ADDRESS = "SET_CURRENT_ADDRESS";
