export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAILED = "GET_PRODUCT_LIST_FAILED";
export const SET_PRODUCT = "SET_PRODUCT";
